### ISSUE TITLE
error on updating transactions

### ISSUE THREAD

**Issue by tulipy** [jotacor/tradunio#1]
Spanish:
--------------------------------------------
Hola, Ayer instalé tu app en mi raspberry pi para mantener controlada mi comunidad.
y estoy recibiendo un error al inicializar la base de datos.

por si te puede ayudar, tengo el mercado en idioma turco para que no puedan ver el dinero mis usuarios en comuniazo

English:
---------------------------------------------

Hello, Yesterday I installed your app in my raspberry to controlled keep my community.
and I am getting an error when initializing the database

----------------------------TERMINAL ERROR---------------------------------------

`
pi@raspberrypi:~/tradunio-master $ sudo python tradunio.py --init
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 53 of the file tradunio.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))

[*] Initializing the database.
        Database contains data, do you want to remove it and load data again? (y/n) y
DELETE FROM tradunio.clubs WHERE 1; done.
DELETE FROM tradunio.owners WHERE 1; done.
DELETE FROM tradunio.players WHERE 1; done.
DELETE FROM tradunio.points WHERE 1; done.
DELETE FROM tradunio.prices WHERE 1; done.
DELETE FROM tradunio.transactions WHERE 1; done.
DELETE FROM tradunio.user_data WHERE 1; done.
DELETE FROM tradunio.users WHERE 1; done.
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 847 of the file tradunio.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Updating users data => done.
Updating transactions =>
Traceback (most recent call last):
  File "tradunio.py", line 847, in <module>
    main()
  File "tradunio.py", line 97, in main
    set_transactions()
  File "tradunio.py", line 477, in set_transactions
    until_date = db.simple_query('SELECT MAX(date) FROM transactions')[0][0] - timedelta(days=10)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'

`

**Comment by jotacor** [comment]
Solved in the commit 80a66363b2f250b54110e56b5b2cb9a26cdf2ca8
Issue is related when the database is initialized for first time, there is no date inside transactions table so it gets NoneType.
Solved checking if NoneType returned and assign today date minus 10 days to get the news from Comunio since then.
